name: Generate Contribution Snake

on:
  schedule:
    # Run automatically every 24 hours at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push Snake SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update animated contribution snake [skip ci]"
          file_pattern: "assets/*.svg"
